[tool.black]
line-length=79

[tool.mypy]
python_version = "3.10"
plugins = ["pydantic.mypy"]
strict = true
explicit_package_bases = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "migrations.*"
ignore_errors = true